spring:
  application:
    name: spring-redis
  cache:
    type: redis
    redis:
      time-to-live: 60s
    cache-names: currencies
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      timeout: 10s
  threads:
    virtual:
      enabled: true

app:
  redis:
    currency:
      keys:
        events: currency-events
        group-name: currency-group
        instance-name: currency-instance
        notifications: currency-notification
        volatility: currency-volatility
        metrics: metrics:currency:read:%s
        rate-limit: ratelimit:%s
        currency: currency:%s

