spring:
  cache:
    type: redis
    redis:
      time-to-live: 60s
    cache-names: prices
  application:
    name: spring-redis
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      username: root
      timeout: 10s
