spring:
  application:
    name: spring-redis
  cache:
    type: redis
    redis:
      time-to-live: 60s
    cache-names: currencies
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      timeout: 10s
  threads:
    virtual:
      enabled: true
